import { QuoteContextProvider } from "@/context";

export const metadata = {
  title: "Random Quotes",
  description: "Generated by firat altun  ",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <QuoteContextProvider>{children}</QuoteContextProvider>
      </body>
    </html>
  );
}
